services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                user: mateus
                uid: 1000
        image: laravel
        container_name: laravel
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - backend

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8800:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - backend
        depends_on:
            - app
    
networks:
    backend:
        driver: bridge